opt_in_rules:
  - sorted_imports
  - modifier_order
  - redundant_nil_coalescing
  - force_unwrapping

disabled_rules:
  - todo
  - trailing_comma

excluded:
  - .build
  - dist
  - DerivedData

line_length: 120
identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y

force_unwrapping:
  severity: error

reporter: emoji
